coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.01%
        base: auto
        paths: "src/"
        branches:
          - master
          - code-coverage-zi
        if_ci_failed: error
        informational: false
        only_pulls: false
    comment:
      layout: "reach, diff, flags, files"
      behavior: default
      require_changes: false  # if true: only post the comment if coverage changes
      require_base: no        # [yes :: must have a base report to post]
      require_head: no       # [yes :: must have a head report to post]
      branches:               # branch names that can post comment
        - master
        - code-coverage-zi
    
